import { createContext, useCallback, useContext, useEffect, useMemo, useState, ReactNode } from "react";

type Theme = "light" | "dark";
type Lang = "en" | "bn";

interface ThemeContextType {
  theme: Theme;
  lang: Lang;
  toggleTheme: () => void;
  toggleLang: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    "brand.name": "Parar Dokan",
    "nav.about": "About",
    "nav.features": "Features",
    "nav.how": "How It Works",
    "nav.pricing": "Pricing",
    "nav.explore": "Explore",
    "nav.dashboard_preview": "Dashboard Preview",
    "nav.network": "Local Network",
    "nav.ledger": "Digital Ledger",
    "nav.contact": "Contact",
    "nav.dashboard": "Dashboard",
    "nav.getStarted": "Get Started",
    "nav.login": "Login",
    "hero.title": "Your Neighborhood, Connected",
    "hero.subtitle":
      "Order from local shops, manage credit, and support businesses around the corner.",
    "hero.cta": "Get Started Free",
    "hero.secondary": "See How It Works",
    "home.network_eyebrow": "A better way to shop local",
    "home.network_title": "Everything your neighborhood needs, closer than ever.",
    "home.network_body": "Parar Dokan connects nearby customers with trusted shopkeepers through one simple, friendly experience.",
    "home.customer_title": "For everyday customers",
    "home.customer_body": "Find open shops, send a plain-language order, choose how to pay, and keep every purchase in one place.",
    "home.shopkeeper_title": "For neighborhood shops",
    "home.shopkeeper_body": "Manage orders, opening hours, customer baki, sales, and payments without losing the personal touch.",
    "home.audience_features_title": "Built around the way you work",
    "home.audience_features_description": "One connected neighborhood platform, with focused tools for customers and shopkeepers.",
    "home.customer_features_eyebrow": "FOR CUSTOMERS",
    "home.customer_features_title": "Shop with confidence",
    "home.customer_features_description": "Find trusted local shops, place simple orders, and keep your credit and payments clear from one dashboard.",
    "home.customer_feature_discover": "Discover shops within your 1 km neighborhood",
    "home.customer_feature_order": "Send clear orders in your own words",
    "home.customer_feature_baki": "Track Baki balances and purchase history",
    "home.customer_feature_payments": "Pay securely with bKash or Nagad",
    "home.shopkeeper_features_eyebrow": "FOR SHOPKEEPERS",
    "home.shopkeeper_features_title": "Run your shop simply",
    "home.shopkeeper_features_description": "Bring orders, customers, Baki, sales, and payments together in a practical workspace made for local business.",
    "home.shopkeeper_feature_orders": "Manage incoming orders and delivery status",
    "home.shopkeeper_feature_baki": "Record customer purchases with clear details",
    "home.shopkeeper_feature_sales": "Track daily sales and customer payments",
    "home.shopkeeper_feature_insights": "See useful activity and performance insights",
    "home.explore_for_role": "Get started",
    "home.feature_customer_eyebrow": "FOR CUSTOMERS",
    "home.feature_shopkeeper_eyebrow": "FOR SHOPKEEPERS",
    "home.feature_discover_title": "Find the right shop nearby",
    "home.feature_discover_description": "See your neighborhood at a glance, compare nearby shops, and choose where to order.",
    "home.feature_profile_title": "Keep your profile connected",
    "home.feature_profile_description": "Update your location and profile once so your dashboard stays personal and useful.",
    "home.feature_baki_title": "Know every balance",
    "home.feature_baki_description": "Follow Baki purchases, balances, and payments without losing track of the details.",
    "home.feature_shopkeeper_title": "Your shop, one clear view",
    "home.feature_shopkeeper_description": "See revenue, orders, customer credit, and daily activity in one practical workspace.",
    "home.ledger_title": "The familiar khata, made clear",
    "home.ledger_body": "Keep credit relationships transparent for both sides. Every balance, payment, and approval stays easy to follow.",
    "home.activity": "Recent activity",
    "home.paid": "Payment received",
    "home.approved": "Baki approved",
    "home.order_ready": "Order ready",
    "home.start_today": "Start building your local circle today",
    "label.about_title": "Built for the corner shop, the daily customer",
    "label.about_intro": "Every neighborhood has its backbone — the grocery store, the pharmacy, the tea stall. Parar Dokan brings these local relationships into the digital age without losing what makes them special: trust, familiarity, and flexibility.",
    "label.about_description": "The traditional baki credit system has worked for generations. We have made it transparent, trackable, and payable from any phone.",
    "label.footer_description": "Connecting neighborhoods with local shopkeepers across Bangladesh.",
    "label.features": "Features",
    "label.pricing": "Pricing",
    "label.how_it_works": "How It Works",
    "label.join_your_neighborhood": "Join your neighborhood",
    "label.shops_count": "500+ Shops",
    "label.across_bangladesh": "Across Bangladesh",
    "label.easy_ordering": "Easy Ordering",
    "label.plain_language_orders": "Plain language orders",
    "label.digital_baki": "Digital Baki",
    "label.credit_made_transparent": "Credit made transparent",
    "label.radius_1km": "1km Radius",
    "label.truly_local": "Truly local",
    "label.features_description": "From discovery to payment — everything your local commerce needs.",
    "label.up_and_running_in_minutes": "Up and running in minutes",
    "label.no_training_needed": "No training needed. No complex setup. Just sign up and go.",
    "label.loved_by_neighborhoods": "Loved by neighborhoods",
    "label.simple_honest_pricing": "Simple, honest pricing",
    "label.frequently_asked_questions": "Frequently asked questions",
    "label.your_neighborhood_is_waiting": "Your neighborhood is waiting",
    "label.join_thousands_connected": "Join thousands of customers and shopkeepers already connected.",
    "faq.customers_pay": "Do customers pay to use Parar Dokan?",
    "faq.customers_pay.answer": "No. The app is completely free for customers. Shopkeepers pay a monthly subscription to manage their shop.",
    "faq.baki": "How does the baki (credit) system work?",
    "faq.baki.answer": "Customers request baki membership from a shop. The shopkeeper verifies and approves them in person. The shopkeeper then updates balances, and customers can pay via bKash or Nagad.",
    "faq.location": "Is my location data safe?",
    "faq.location.answer": "Your location is only used to show nearby shops. We store it securely and never share it with third parties.",
    "faq.switch_role": "Can I switch between customer and shopkeeper?",
    "faq.switch_role.answer": "Roles are set once during registration to prevent confusion. If you need to change your role, contact our support team.",
    "features.title": "Everything Your Neighborhood Needs",
    "features.shops": "Discover Local Shops",
    "features.shops.desc":
      "Find open shops near you on a live map within 1 km.",
    "features.orders": "Easy Ordering",
    "features.orders.desc":
      "Place orders in plain language — no complex menus needed.",
    "features.baki": "Digital Baki",
    "features.baki.desc":
      "Manage credit relationships digitally, transparently.",
    "features.payments": "Secure Payments",
    "features.payments.desc": "Pay via bKash or Nagad with transaction verification.",
    "label.step_create_account": "Create Your Account",
    "label.step_create_account_desc": "Sign up as a customer or shopkeeper. One tap with Google, email, or phone.",
    "label.step_discover_shops": "Discover Local Shops",
    "label.step_discover_shops_desc": "Find open shops within 1 km of you on a live map.",
    "label.step_order_pay": "Order & Pay",
    "label.step_order_pay_desc": "Write your order in plain language. Pay securely or use your baki credit.",
    "label.testimonial_rina": "I order my daily groceries from Karim Bhai's shop now without leaving home. The baki system is exactly like the old way but digital.",
    "label.testimonial_karim": "Managing credit used to be in a notebook. Now I track everything digitally and my customers can pay anytime.",
    "label.testimonial_nusrat": "Found three shops near me I never knew existed. The app is simple — my elderly mother can use it too.",
    "label.customer_mirpur": "Customer, Mirpur",
    "label.shopkeeper_mirpur": "Shopkeeper, Mirpur",
    "label.customer_uttara": "Customer, Uttara",
    "label.basic": "Basic",
    "label.standard": "Standard",
    "label.premium": "Premium",
    "label.per_month": "/month",
    "label.up_to_50_orders": "Up to 50 orders/month",
    "label.unlimited_orders": "Unlimited orders",
    "label.baki_management": "Baki management",
    "label.basic_analytics": "Basic analytics",
    "label.advanced_analytics": "Advanced analytics",
    "label.email_support": "Email support",
    "label.priority_support": "Priority support",
    "label.everything_standard": "Everything in Standard",
    "label.multiple_shop_support": "Multiple shop support",
    "label.custom_branding": "Custom branding",
    "label.dedicated_support": "Dedicated support",
    "dashboard.overview": "Overview",
    "dashboard.shops": "Nearby Shops",
    "dashboard.orders": "Orders",
    "dashboard.baki": "My Baki",
    "dashboard.payments": "Payments",
    "dashboard.profile": "Profile",
    "dashboard.sales": "Sales",
    "dashboard.logout": "Logout",
    "dashboard.customer_space": "Customer space",
    "dashboard.shopkeeper_space": "Shopkeeper space",
    "dashboard.welcome_back_name": "Welcome back",
    "dashboard.neighborhood_commerce": "Your neighborhood commerce",
    "dashboard.nearby_simple_connected": "Nearby, simple, connected",
    "contact.eyebrow": "CONTACT THE TEAM",
    "contact.title": "Let’s make your neighborhood work better.",
    "contact.description": "Have a question, partnership idea, or need help getting started? Send us a message and our team will get back to you.",
    "contact.name": "Your name",
    "contact.email": "Email address",
    "contact.subject": "Subject",
    "contact.message": "How can we help?",
    "contact.send": "Send message",
    "contact.sending": "Sending message...",
    "contact.success": "Thanks! Your message has been sent.",
    "contact.error": "We could not send your message. Please try again.",
    "contact.config_error": "Contact service is not configured yet. Please email us directly.",
    "contact.email_label": "Email us directly",
    "overview.customer_matrix": "CUSTOMER MATRIX / LIVE",
    "overview.shopkeeper_matrix": "SHOPKEEPER MATRIX / LIVE",
    "overview.neighborhood_signal": "NEIGHBORHOOD SIGNAL",
    "overview.neighborhood_title": "Your local commerce network at a glance.",
    "overview.live_connection": "Live connection",
    "overview.active_orders": "ACTIVE ORDERS",
    "overview.credit_balance": "CREDIT BALANCE",
    "overview.payment_flow": "PAYMENT FLOW",
    "overview.awaiting_action": "awaiting action",
    "overview.across_shops": "across shops",
    "overview.recent_records": "recent records",
    "overview.shop_signal": "SHOP PERFORMANCE SIGNAL",
    "overview.shop_title": "Track the health of your store in one view.",
    "overview.accepting_orders": "Accepting orders",
    "overview.offline_mode": "Offline mode",
    "overview.todays_revenue": "TODAY'S REVENUE",
    "overview.order_queue": "ORDER QUEUE",
    "overview.baki_exposure": "BAKI EXPOSURE",
    "overview.sales_logged": "sales logged",
    "overview.needs_attention": "needs attention",
    "overview.customers": "customers",
    "overview.total_orders": "Total Orders",
    "overview.pending_orders": "Pending Orders",
    "overview.payments": "Payments",
    "overview.total_baki": "Total Baki Owed",
    "overview.total_sales": "Total Sales",
    "overview.activity_trend": "Activity trend",
    "overview.last_seven_days": "Last 7 days",
    "overview.order_pulse": "Order pulse",
    "overview.daily_volume": "Daily volume",
    "overview.orders": "Orders",
    "overview.revenue": "Revenue",
    "nearby.within_radius": "Shops within 1 km of your location",
    "nearby.distance_away": "away",
    "nearby.your_location": "Your location",
    "nearby.open": "Open",
    "nearby.closed": "Closed",
    "nearby.order": "Order",
    "nearby.baki": "Baki",
    "nearby.no_shops": "No shops found nearby",
    "auth.verify_email": "Please verify your email before signing in.",
    "auth.verification_sent": "A verification email was sent. Verify your email, then sign in.",
    "auth.forgot_password": "Forgot password?",
    "auth.reset_sent": "Password reset email sent. Check your inbox.",
    "auth.reset_failed": "Could not send the reset email. Check the address and try again.",
    "label.pin_your_location": "Pin your location",
    "label.shop_name": "Shop Name",
    "label.email": "Email",
    "label.password": "Password",
    "label.address": "Address",
    "label.location": "Location",
    "label.gender": "Gender",
    "label.male": "Male",
    "label.female": "Female",
    "label.other": "Other",
    "label.phone": "Phone",
    "label.balance": "Balance",
    "label.actions": "Actions",
    "label.quick_order": "Quick order",
    "label.describe_what_you_need_and_send_it_to_a_nearby_shop": "Describe what you need and send it to a nearby shop.",
    "label.try_it_now": "Try it now",
    "label.for_shopkeepers_customers_use_the_app_free": "For shopkeepers. Customers use the app free.",
    "label.your_neighborhood_at_a_glance": "Your neighborhood at a glance",
    "label.a_simple_dashboard_for_orders_baki_and_local_shops": "A simple dashboard for orders, baki, and local shops.",
    "label.good_morning_rina": "Good morning, Rina",
    "label.customer_dashboard": "Customer Dashboard",
    "label.now_live_across_bangladesh": "Now live across Bangladesh",
    "label.local_shops": "Local shops",
    "label.active_users": "Active users",
    "label.orders_day": "Orders/day",
    "label.all_systems_live": "All systems live",
    "label.total_orders": "Total Orders",
    "label.baki_balance": "Baki Balance",
    "label.preparing": "Preparing",
    "label.delivered": "Delivered",
    "label.product": "Product",
    "label.resources": "Resources",
    "label.company": "Company",
    "label.documentation": "Documentation",
    "label.help_center": "Help Center",
    "label.blog": "Blog",
    "label.about": "About",
    "label.careers": "Careers",
    "label.privacy_policy": "Privacy Policy",
    "label.terms_of_service": "Terms of Service",
    "label.create_account": "Create Account",
    "label.send_otp": "Send OTP",
    "label.verify_otp": "Verify OTP",
    "label.google": "Google",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.preparing": "Preparing",
    "status.delivered": "Delivered",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    "status.paid": "Paid",
    "status.failed": "Failed",
    "status.verified": "Verified",
    "shop.open": "Open",
    "shop.closed": "Closed",
    "label.quick_actions": "Quick Actions",
    "label.find_nearby_shops": "Find Nearby Shops",
    "label.shops_within_1_km": "Shops within 1 km",
    "label.place_an_order": "Place an Order",
    "label.order_from_a_shop": "Order from a shop",
    "label.recent_orders": "Recent Orders",
    "label.no_payments_yet": "No payments yet",
    "label.payment_history": "Payment History",
    "label.pay_baki_balance": "Pay Baki Balance",
    "label.select_baki": "Select Baki",
    "label.amount_bdt": "Amount (BDT)",
    "label.payment_method": "Payment Method",
    "label.my_profile": "My Profile",
    "label.manage_your_account_information": "Manage your account information",
    "label.full_name": "Full Name",
    "label.phone_number": "Phone Number",
    "label.prefer_not_to_say": "Prefer not to say",
    "label.my_baki": "My Baki",
    "label.request_baki_membership": "Request Baki Membership",
    "label.request": "Request",
    "label.add": "Add",
    "label.save": "Save",
    "label.active_members": "Active Members",
    "label.purchase_history": "Purchase history",
    "label.product_details": "Product details",
    "label.phone_unavailable": "Phone unavailable",
    "label.address_unavailable": "Address unavailable",
    "label.open": "Open",
    "label.closed": "Closed",
    "label.open_by_schedule_button": "Open by schedule",
    "label.closed_by_schedule_button": "Closed by schedule",
    "label.save_opening_hours": "Save opening hours",
    "label.update_failed": "Update failed",
    "label.schedule_updated": "Opening schedule updated successfully",
    "label.shopkeeper_confirms_final_amount_placeholder": "Shopkeeper confirms the final amount",
    "label.select_baki_enter_amount": "Select baki and enter amount",
    "label.payment_failed": "Payment failed",
    "label.delete_sale_confirm": "Delete this sale record?",
    "label.credit_limit": "Credit limit",
    "label.limit": "Limit",
    "label.no_limit": "No limit",
    "label.set_credit_limit": "Set limit",
    "label.add_credit_customer": "Add credit customer",
    "label.add_purchase": "Add purchase",
    "label.member_id": "Member ID",
    "label.customer_details": "Customer details",
    "label.credit_customer_details": "Credit customer details",
    "label.view_details": "View details",
    "label.remove": "Remove",
    "label.remove_baki_member": "Remove Baki member",
    "label.confirm_delete": "Confirm delete?",
    "label.confirm_update": "Confirm update?",
    "label.confirm_update_description": "Do you want to save this update?",
    "label.update_success": "Updated successfully",
    "label.delete_success": "Deleted successfully",
    "label.credit_customer_nid_help": "Save the customer's details and both sides of their NID for your credit records.",
    "label.nid_number": "NID number",
    "label.nid_front": "NID front photo",
    "label.nid_back": "NID back photo",
    "label.search_credit_members": "Search by ID, name, phone, or email",
    "nearby.use_current_location": "Use current location",
    "nearby.using_saved_location": "Using your saved profile location",
    "nearby.set_location_first": "Set your location in your profile or use your current location.",
    "nearby.location_permission": "Location access was denied or unavailable. Allow it in your browser and try again.",
    "nearby.location_unavailable": "This browser does not support location access.",
    "label.no_baki_memberships_yet": "No baki memberships yet",
    "label.outstanding": "Outstanding",
    "label.track_all_your_orders": "Track all your orders",
    "label.no_orders_yet": "No orders yet",
    "label.place_your_first_order_from_a_nearby_shop": "Place your first order from a nearby shop",
    "label.nearby_shops": "Nearby Shops",
    "label.live": "Live",
    "label.baki": "Baki",
    "label.nearby": "Nearby",
    "label.closest_shop": "Closest shop",
    "label.open_shops_near_you": "Open shops near you",
    "label.everything_in_one_view": "Everything in one view",
    "label.current_balance": "Current balance",
    "label.monthly_limit": "Monthly limit",
    "label.local_first": "Local-first",
    "label.discovery_1km": "1km discovery",
    "label.secure_checkout": "Secure checkout",
    "label.no_shops_found_nearby": "No shops found nearby",
    "label.order_placed": "Order Placed!",
    "label.quantity": "Quantity",
    "label.payment_option": "Payment option",
    "label.not_approved_for_this_shop": "Not approved for this shop",
    "label.estimated_amount_bdt": "Estimated amount (BDT)",
    "label.online_payment_provider": "Online payment provider",
    "label.choose_a_nearby_shop": "Choose a nearby shop...",
    "label.what_do_you_need": "What do you need?",
    "label.delivery_notes": "Delivery notes",
    "label.optional": "Optional",
    "label.todays_revenue": "Today's Revenue",
    "label.total_revenue": "Total Revenue",
    "label.avg_sale": "Avg. Sale",
    "label.sales_count": "sales",
    "label.total_sales": "total sales",
    "label.per_transaction": "per transaction",
    "label.rice_placeholder": "e.g. Rice 2kg",
    "label.optional_note": "Optional note",
    "label.open_by_schedule": "Open by schedule",
    "label.closed_by_schedule": "Closed by schedule",
    "label.manage_customer_credit_accounts": "Manage customer credit accounts",
    "label.nearby_customers": "Nearby customers",
    "label.add_to_baki": "Add to baki",
    "label.add_baki_customer_manually": "Add Baki Customer Manually",
    "label.no_active_baki_members": "No active baki members",
    "label.orders": "Orders",
    "label.manage_incoming_customer_orders": "Manage incoming customer orders",
    "label.all_orders": "All Orders",
    "label.no_orders_found": "No orders found",
    "label.not_specified": "Not specified",
    "label.final_amount_bdt": "Final amount (BDT)",
    "label.update": "Update",
    "label.sales": "Sales",
    "label.track_your_daily_sales": "Track your daily sales",
    "label.record_new_sale": "Record New Sale",
    "label.item_name": "Item Name *",
    "label.item": "Item",
    "label.select_shop": "Select shop",
    "label.price": "Price (?) *",
    "label.customer_name": "Customer Name",
    "label.customer_phone": "Customer Phone",
    "label.note": "Note",
    "label.no_sales_recorded_yet": "No sales recorded yet",
    "label.shop": "Shop",
    "label.items": "Items",
    "label.status": "Status",
    "label.date": "Date",
    "label.customer": "Customer",
    "label.amount": "Amount",
    "label.method": "Method",
    "label.action": "Action",
    "label.shop_profile": "Shop & Profile",
    "label.manage_your_shop_and_personal_info": "Manage your shop and personal info",
    "label.opening_hours": "Opening hours",
    "label.use_schedule": "Use schedule",
    "label.personal_information": "Personal Information",
    "label.shop_location": "Shop location",
    "label.save_changes": "Save Changes",
    "label.subscription_plan": "Subscription Plan",
    "label.popular": "Popular",
    "label.review_and_verify_customer_payments": "Review and verify customer payments",
    "label.welcome_back": "Welcome back",
    "label.hello": "Hello",
    "label.welcome": "Welcome",
    "label.customer_space": "Customer space",
    "label.shopkeeper_space": "Shopkeeper space",
    "label.your_shop_dashboard": "Your shop dashboard",
    "label.view_all": "View all",
    "label.shop_is_open": "Shop is Open",
    "label.shop_is_closed": "Shop is Closed",
    "label.neighborhood_update": "Here's what's happening in your neighborhood today.",
    "label.create_your_account": "Create your account",
    "label.sign_in_to_your_neighborhood": "Sign in to your neighborhood",
    "label.join_parar_dokan_today": "Join Parar Dokan today",
    "label.sign_in": "Sign In",
    "label.register": "Register",
    "label.i_am_a": "I am a...",
    "label.avatar": "Avatar",
    "label.payments": "Payments",
    "label.pay_your_baki_balance": "Pay your baki balance",
    "label.choose": "Choose...",
    "label.enter_amount": "Enter amount",
    "label.my_orders": "My Orders",
    "label.items_colon": "Items:",
    "label.quantity_colon": "Quantity:",
    "label.total_received": "Total Received",
    "label.pending": "Pending",
    "label.verified": "Verified",
    "label.confirm_delete_sale": "Delete this sale record?",
    "label.customers_within_1km": "Customers within 1 km of your shop who are not in your baki list.",
    "label.shopkeeper_confirms_amount": "Shopkeeper confirms the final amount",
    "label.required_to_approve": "Required to approve",
    "label.select_shop_label": "Select Shop",
    "label.enter_quantity": "e.g. 2 kg, 500 g, 1 bottle",
    "label.order_placeholder": "e.g. 2 kg rice, 500g sugar, 1 bottle of cooking oil, 6 eggs...",
    "label.delivery_placeholder": "e.g. Please deliver before 6 PM",
    "label.your_neighborhood": "Your neighborhood",
    "label.customer_name_placeholder": "Customer name",
    "label.phone_number_placeholder": "Phone number",
  },
  bn: {
    "brand.name": "পাড়ার দোকান",
    "nav.about": "সম্পর্কে",
    "nav.features": "বৈশিষ্ট্য",
    "nav.how": "কীভাবে কাজ করে",
    "nav.pricing": "মূল্য",
    "nav.explore": "আরও দেখুন",
    "nav.dashboard_preview": "ড্যাশবোর্ড প্রিভিউ",
    "nav.network": "স্থানীয় নেটওয়ার্ক",
    "nav.ledger": "ডিজিটাল খাতা",
    "nav.contact": "যোগাযোগ",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.getStarted": "শুরু করুন",
    "nav.login": "লগইন",
    "hero.title": "আপনার পাড়া, এখন সংযুক্ত",
    "hero.subtitle":
      "স্থানীয় দোকান থেকে অর্ডার করুন, বাকি ব্যবস্থাপনা করুন।",
    "hero.cta": "বিনামূল্যে শুরু করুন",
    "hero.secondary": "কীভাবে কাজ করে দেখুন",
    "home.network_eyebrow": "স্থানীয় কেনাকাটার সহজ পথ",
    "home.network_title": "আপনার পাড়ার সব প্রয়োজন, এখন আরও কাছে।",
    "home.network_body": "পাড়ার দোকান ক্রেতা ও বিশ্বস্ত দোকানদারদের একটি সহজ ও পরিচিত অভিজ্ঞতায় যুক্ত করে।",
    "home.customer_title": "প্রতিদিনের ক্রেতাদের জন্য",
    "home.customer_body": "খোলা দোকান খুঁজুন, সহজ ভাষায় অর্ডার পাঠান, পেমেন্টের পদ্ধতি বেছে নিন এবং সব কেনাকাটা এক জায়গায় রাখুন।",
    "home.shopkeeper_title": "পাড়ার দোকানদারদের জন্য",
    "home.shopkeeper_body": "ব্যক্তিগত সম্পর্ক অক্ষুণ্ণ রেখে অর্ডার, খোলার সময়, বাকি, বিক্রয় ও পেমেন্ট পরিচালনা করুন।",
    "home.audience_features_title": "আপনার কাজের ধরন অনুযায়ী তৈরি",
    "home.audience_features_description": "একটি সংযুক্ত পাড়ার প্ল্যাটফর্ম, যেখানে ক্রেতা ও দোকানদার উভয়ের জন্য আলাদা কার্যকর টুল রয়েছে।",
    "home.customer_features_eyebrow": "ক্রেতাদের জন্য",
    "home.customer_features_title": "নিশ্চিন্তে কেনাকাটা করুন",
    "home.customer_features_description": "বিশ্বস্ত স্থানীয় দোকান খুঁজুন, সহজে অর্ডার দিন এবং এক ড্যাশবোর্ড থেকে বাকি ও পেমেন্ট পরিষ্কারভাবে দেখুন।",
    "home.customer_feature_discover": "আপনার ১ কিমি এলাকার দোকান খুঁজুন",
    "home.customer_feature_order": "নিজের ভাষায় পরিষ্কার অর্ডার পাঠান",
    "home.customer_feature_baki": "বাকির ব্যালেন্স ও কেনাকাটার ইতিহাস দেখুন",
    "home.customer_feature_payments": "বিকাশ বা নগদ দিয়ে নিরাপদে পেমেন্ট করুন",
    "home.shopkeeper_features_eyebrow": "দোকানদারদের জন্য",
    "home.shopkeeper_features_title": "সহজভাবে দোকান পরিচালনা করুন",
    "home.shopkeeper_features_description": "স্থানীয় ব্যবসার জন্য তৈরি একটি বাস্তবসম্মত ওয়ার্কস্পেসে অর্ডার, ক্রেতা, বাকি, বিক্রয় ও পেমেন্ট একসাথে পরিচালনা করুন।",
    "home.shopkeeper_feature_orders": "আসা অর্ডার ও ডেলিভারির অবস্থা পরিচালনা করুন",
    "home.shopkeeper_feature_baki": "পরিষ্কার বিবরণসহ ক্রেতার কেনাকাটা রেকর্ড করুন",
    "home.shopkeeper_feature_sales": "দৈনিক বিক্রয় ও ক্রেতার পেমেন্ট দেখুন",
    "home.shopkeeper_feature_insights": "কার্যক্রম ও ব্যবসার দরকারি তথ্য দেখুন",
    "home.explore_for_role": "শুরু করুন",
    "home.feature_customer_eyebrow": "ক্রেতাদের জন্য",
    "home.feature_shopkeeper_eyebrow": "দোকানদারদের জন্য",
    "home.feature_discover_title": "কাছের সঠিক দোকান খুঁজুন",
    "home.feature_discover_description": "এক নজরে আপনার এলাকা দেখুন, কাছের দোকান তুলনা করুন এবং কোথায় অর্ডার করবেন তা বেছে নিন।",
    "home.feature_profile_title": "আপনার প্রোফাইল সংযুক্ত রাখুন",
    "home.feature_profile_description": "একবার অবস্থান ও প্রোফাইল আপডেট করুন, যাতে ড্যাশবোর্ড আপনার জন্য আরও কার্যকর থাকে।",
    "home.feature_baki_title": "প্রতিটি ব্যালেন্স জানুন",
    "home.feature_baki_description": "বাকির কেনাকাটা, ব্যালেন্স ও পেমেন্টের সব বিবরণ সহজে অনুসরণ করুন।",
    "home.feature_shopkeeper_title": "এক নজরে আপনার দোকান",
    "home.feature_shopkeeper_description": "একটি বাস্তবসম্মত ওয়ার্কস্পেসে আয়, অর্ডার, ক্রেতার বাকি ও দৈনিক কার্যক্রম দেখুন।",
    "home.ledger_title": "পরিচিত খাতা, এখন আরও স্বচ্ছ",
    "home.ledger_body": "দুই পক্ষের ক্রেডিট সম্পর্ক স্বচ্ছ রাখুন। প্রতিটি ব্যালেন্স, পেমেন্ট ও অনুমোদন সহজে দেখা যাবে।",
    "home.activity": "সাম্প্রতিক কার্যক্রম",
    "home.paid": "পেমেন্ট পাওয়া গেছে",
    "home.approved": "বাকি অনুমোদিত",
    "home.order_ready": "অর্ডার প্রস্তুত",
    "home.start_today": "আজই আপনার স্থানীয় নেটওয়ার্ক শুরু করুন",
    "label.about_title": "কাছের দোকান ও প্রতিদিনের ক্রেতাদের জন্য তৈরি",
    "label.about_intro": "প্রতিটি পাড়ারই কিছু ভরসার জায়গা আছে—মুদি দোকান, ফার্মেসি, চায়ের দোকান। পাড়ার দোক এই সম্পর্কগুলোকে ডিজিটাল যুগে নিয়ে আসে, বিশ্বাস, পরিচিতি ও সুবিধা অক্ষুণ্ণ রেখে।",
    "label.about_description": "প্রজন্মের পর প্রজন্ম ধরে চলে আসা বাকি ব্যবস্থাকে আমরা স্বচ্ছ, হিসাবযোগ্য এবং যেকোনো ফোন থেকে পরিশোধযোগ্য করেছি।",
    "label.footer_description": "বাংলাদেশজুড়ে পাড়া ও স্থানীয় দোকানদারদের সংযুক্ত করছি।",
    "label.features": "বৈশিষ্ট্য",
    "label.pricing": "মূল্য",
    "label.how_it_works": "কীভাবে কাজ করে",
    "label.join_your_neighborhood": "আপনার পাড়ায় যোগ দিন",
    "label.shops_count": "৫০০+ দোকান",
    "label.across_bangladesh": "বাংলাদেশজুড়ে",
    "label.easy_ordering": "সহজ অর্ডার",
    "label.plain_language_orders": "সহজ ভাষায় অর্ডার",
    "label.credit_made_transparent": "স্বচ্ছ ক্রেডিট ব্যবস্থা",
    "label.radius_1km": "১ কিমি পরিধি",
    "label.truly_local": "সত্যিই স্থানীয়",
    "label.features_description": "দোকান খোঁজা থেকে পেমেন্ট পর্যন্ত—স্থানীয় কেনাকাটার সব সুবিধা একসাথে।",
    "label.up_and_running_in_minutes": "কয়েক মিনিটেই শুরু করুন",
    "label.no_training_needed": "কোনো প্রশিক্ষণ বা জটিল সেটআপ দরকার নেই। নিবন্ধন করুন এবং শুরু করুন।",
    "label.loved_by_neighborhoods": "পাড়ার মানুষের পছন্দ",
    "label.simple_honest_pricing": "সহজ ও স্বচ্ছ মূল্য",
    "label.frequently_asked_questions": "সাধারণ জিজ্ঞাসা",
    "label.your_neighborhood_is_waiting": "আপনার পাড়া অপেক্ষা করছে",
    "label.join_thousands_connected": "ইতোমধ্যে যুক্ত হাজারো ক্রেতা ও দোকানদারের সাথে যোগ দিন।",
    "faq.customers_pay": "পাড়ার দোকান ব্যবহার করতে কি ক্রেতাদের টাকা দিতে হয়?",
    "faq.customers_pay.answer": "না। ক্রেতাদের জন্য অ্যাপটি সম্পূর্ণ বিনামূল্যে। দোকান পরিচালনার জন্য দোকানদাররা মাসিক সাবস্ক্রিপশন দেন।",
    "faq.baki": "বাকি (ক্রেডিট) ব্যবস্থা কীভাবে কাজ করে?",
    "faq.baki.answer": "ক্রেতা দোকানে বাকি সদস্যপদের অনুরোধ করেন। দোকানদার যাচাই করে অনুমোদন করেন। এরপর দোকানদার ব্যালেন্স আপডেট করেন এবং ক্রেতা বিকাশ বা নগদ দিয়ে পরিশোধ করতে পারেন।",
    "faq.location": "আমার অবস্থানের তথ্য কি নিরাপদ?",
    "faq.location.answer": "আপনার অবস্থান শুধু কাছের দোকান দেখানোর জন্য ব্যবহার করা হয়। আমরা এটি নিরাপদে সংরক্ষণ করি এবং তৃতীয় পক্ষের সাথে শেয়ার করি না।",
    "faq.switch_role": "আমি কি ক্রেতা ও দোকানদারের মধ্যে পরিবর্তন করতে পারি?",
    "faq.switch_role.answer": "ভুল বোঝাবুঝি এড়াতে নিবন্ধনের সময় ভূমিকা নির্ধারিত হয়। পরিবর্তনের প্রয়োজন হলে সহায়তা দলের সাথে যোগাযোগ করুন।",
    "features.title": "আপনার পাড়ার জন্য সবকিছু",
    "features.shops": "স্থানীয় দোকান খুঁজুন",
    "features.shops.desc": "১ কিমি এলাকার মধ্যে খোলা দোকান খুঁজুন।",
    "features.orders": "সহজ অর্ডার",
    "features.orders.desc": "সাধারণ ভাষায় অর্ডার দিন।",
    "features.baki": "ডিজিটাল বাকি",
    "features.baki.desc": "বাকি ব্যবস্থাপনা ডিজিটালভাবে করুন।",
    "features.payments": "নিরাপদ পেমেন্ট",
    "features.payments.desc": "স্ট্রাইপ বা এসএসএলকমার্জ দিয়ে পেমেন্ট করুন।",
    "label.step_create_account": "অ্যাকাউন্ট তৈরি করুন",
    "label.step_create_account_desc": "ক্রেতা বা দোকানদার হিসেবে নিবন্ধন করুন। Google, ইমেইল বা ফোনে এক ট্যাপেই শুরু করুন।",
    "label.step_discover_shops": "স্থানীয় দোকান খুঁজুন",
    "label.step_discover_shops_desc": "লাইভ ম্যাপে ১ কিমির মধ্যে খোলা দোকান খুঁজে নিন।",
    "label.step_order_pay": "অর্ডার ও পেমেন্ট",
    "label.step_order_pay_desc": "সহজ ভাষায় অর্ডার লিখুন। নিরাপদে পেমেন্ট করুন বা বাকি ব্যবহার করুন।",
    "label.testimonial_rina": "এখন ঘর থেকে বের না হয়েই করিম ভাইয়ের দোকান থেকে প্রতিদিনের বাজার করি। বাকি ব্যবস্থাটি আগের মতোই, শুধু ডিজিটাল।",
    "label.testimonial_karim": "আগে খাতায় ক্রেডিট লিখে রাখতাম। এখন সবকিছু ডিজিটালভাবে দেখি এবং ক্রেতারা যেকোনো সময় পরিশোধ করতে পারেন।",
    "label.testimonial_nusrat": "আমার কাছেই তিনটি দোকান পেয়েছি যেগুলোর কথা আগে জানতাম না। অ্যাপটি এত সহজ যে আমার বৃদ্ধ মাও ব্যবহার করতে পারেন।",
    "label.customer_mirpur": "ক্রেতা, মিরপুর",
    "label.shopkeeper_mirpur": "দোকানদার, মিরপুর",
    "label.customer_uttara": "ক্রেতা, উত্তরা",
    "label.basic": "বেসিক",
    "label.standard": "স্ট্যান্ডার্ড",
    "label.premium": "প্রিমিয়াম",
    "label.per_month": "/মাস",
    "label.up_to_50_orders": "মাসে ৫০টি পর্যন্ত অর্ডার",
    "label.unlimited_orders": "আনলিমিটেড অর্ডার",
    "label.basic_analytics": "বেসিক অ্যানালিটিক্স",
    "label.advanced_analytics": "অ্যাডভান্সড অ্যানালিটিক্স",
    "label.email_support": "ইমেইল সহায়তা",
    "label.priority_support": "অগ্রাধিকার সহায়তা",
    "label.everything_standard": "স্ট্যান্ডার্ডের সব সুবিধা",
    "label.multiple_shop_support": "একাধিক দোকান সহায়তা",
    "label.custom_branding": "নিজস্ব ব্র্যান্ডিং",
    "label.dedicated_support": "নির্দিষ্ট সহায়তা",
    "dashboard.overview": "সংক্ষিপ্ত বিবরণ",
    "dashboard.shops": "কাছের দোকান",
    "dashboard.orders": "অর্ডার",
    "dashboard.baki": "আমার বাকি",
    "dashboard.payments": "পেমেন্ট",
    "dashboard.profile": "প্রোফাইল",
    "dashboard.sales": "বিক্রয়",
    "dashboard.logout": "লগআউট",
    "dashboard.customer_space": "ক্রেতার অংশ",
    "dashboard.shopkeeper_space": "দোকানদারের অংশ",
    "dashboard.welcome_back_name": "আবার স্বাগতম",
    "dashboard.neighborhood_commerce": "আপনার এলাকার বাণিজ্য",
    "dashboard.nearby_simple_connected": "কাছাকাছি, সহজ, সংযুক্ত",
    "contact.eyebrow": "যোগাযোগ করুন",
    "contact.title": "আপনার এলাকার অভিজ্ঞতা আরও ভালো করি।",
    "contact.description": "প্রশ্ন, অংশীদারত্বের প্রস্তাব বা শুরু করার সহায়তা দরকার? বার্তা পাঠান, আমাদের টিম আপনার সাথে যোগাযোগ করবে।",
    "contact.name": "আপনার নাম",
    "contact.email": "ইমেইল ঠিকানা",
    "contact.subject": "বিষয়",
    "contact.message": "কীভাবে সহায়তা করতে পারি?",
    "contact.send": "বার্তা পাঠান",
    "contact.sending": "বার্তা পাঠানো হচ্ছে...",
    "contact.success": "ধন্যবাদ! আপনার বার্তা পাঠানো হয়েছে।",
    "contact.error": "বার্তা পাঠানো যায়নি। আবার চেষ্টা করুন।",
    "contact.config_error": "যোগাযোগ সেবা এখনো কনফিগার করা হয়নি। সরাসরি ইমেইল করুন।",
    "contact.email_label": "সরাসরি ইমেইল করুন",
    "overview.customer_matrix": "ক্রেতা ম্যাট্রিক্স / লাইভ",
    "overview.shopkeeper_matrix": "দোকানদার ম্যাট্রিক্স / লাইভ",
    "overview.neighborhood_signal": "এলাকার কার্যক্রম",
    "overview.neighborhood_title": "আপনার স্থানীয় বাণিজ্যিক নেটওয়ার্ক এক নজরে দেখুন।",
    "overview.live_connection": "লাইভ সংযোগ",
    "overview.active_orders": "সক্রিয় অর্ডার",
    "overview.credit_balance": "ক্রেডিট ব্যালেন্স",
    "overview.payment_flow": "পেমেন্ট প্রবাহ",
    "overview.awaiting_action": "পদক্ষেপের অপেক্ষায়",
    "overview.across_shops": "টি দোকানে",
    "overview.recent_records": "সাম্প্রতিক রেকর্ড",
    "overview.shop_signal": "দোকানের কার্যক্ষমতার সংকেত",
    "overview.shop_title": "এক জায়গায় আপনার দোকানের অবস্থা পর্যবেক্ষণ করুন।",
    "overview.accepting_orders": "অর্ডার গ্রহণ চলছে",
    "overview.offline_mode": "অফলাইন মোড",
    "overview.todays_revenue": "আজকের আয়",
    "overview.order_queue": "অর্ডার তালিকা",
    "overview.baki_exposure": "বাকি দায়",
    "overview.sales_logged": "টি বিক্রয় নথিভুক্ত",
    "overview.needs_attention": "মনোযোগ প্রয়োজন",
    "overview.customers": "জন ক্রেতা",
    "overview.total_orders": "মোট অর্ডার",
    "overview.pending_orders": "অপেক্ষমাণ অর্ডার",
    "overview.payments": "পেমেন্ট",
    "overview.total_baki": "মোট বাকি",
    "overview.total_sales": "মোট বিক্রয়",
    "overview.activity_trend": "কার্যক্রমের ধারা",
    "overview.last_seven_days": "গত ৭ দিন",
    "overview.order_pulse": "অর্ডারের গতি",
    "overview.daily_volume": "দৈনিক পরিমাণ",
    "overview.orders": "অর্ডার",
    "overview.revenue": "আয়",
    "nearby.within_radius": "আপনার অবস্থান থেকে ১ কিমির মধ্যে দোকান",
    "nearby.distance_away": "দূরে",
    "nearby.your_location": "আপনার অবস্থান",
    "nearby.open": "খোলা",
    "nearby.closed": "বন্ধ",
    "nearby.order": "অর্ডার",
    "nearby.baki": "বাকি",
    "nearby.no_shops": "কাছাকাছি কোনো দোকান পাওয়া যায়নি",
    "auth.verify_email": "সাইন ইন করার আগে আপনার ইমেইল যাচাই করুন।",
    "auth.verification_sent": "যাচাইকরণ ইমেইল পাঠানো হয়েছে। ইমেইল যাচাই করে আবার সাইন ইন করুন।",
    "auth.forgot_password": "পাসওয়ার্ড ভুলে গেছেন?",
    "auth.reset_sent": "পাসওয়ার্ড রিসেট ইমেইল পাঠানো হয়েছে। ইনবক্স দেখুন।",
    "auth.reset_failed": "রিসেট ইমেইল পাঠানো যায়নি। ঠিকানা যাচাই করে আবার চেষ্টা করুন।",
    "status.pending": "অপেক্ষমাণ",
    "status.approved": "অনুমোদিত",
    "status.rejected": "প্রত্যাখ্যাত",
    "status.preparing": "প্রস্তুতি",
    "status.delivered": "ডেলিভারি হয়েছে",
    "status.completed": "সম্পন্ন",
    "status.cancelled": "বাতিল",
    "status.paid": "পরিশোধিত",
    "status.failed": "ব্যর্থ",
    "status.verified": "যাচাইকৃত",
    "shop.open": "খোলা",
    "shop.closed": "বন্ধ",
    "label.pin_your_location": "আপনার অবস্থান নির্ধারণ করুন",
    "label.shop_name": "দোকানের নাম",
    "label.email": "ইমেইল",
    "label.password": "পাসওয়ার্ড",
    "label.address": "ঠিকানা",
    "label.location": "অবস্থান",
    "label.gender": "লিঙ্গ",
    "label.male": "পুরুষ",
    "label.female": "নারী",
    "label.other": "অন্যান্য",
    "label.phone": "ফোন",
    "label.balance": "ব্যালেন্স",
    "label.actions": "অ্যাকশন",
    "label.quick_order": "দ্রুত অর্ডার",
    "label.describe_what_you_need_and_send_it_to_a_nearby_shop": "আপনার প্রয়োজনীয় জিনিস লিখে কাছের দোকানে পাঠান।",
    "label.try_it_now": "এখনই চেষ্টা করুন",
    "label.for_shopkeepers_customers_use_the_app_free": "দোকানদারদের জন্য। ক্রেতারা বিনামূল্যে অ্যাপ ব্যবহার করেন।",
    "label.your_neighborhood_at_a_glance": "এক নজরে আপনার পাড়া",
    "label.a_simple_dashboard_for_orders_baki_and_local_shops": "অর্ডার, বাকি এবং স্থানীয় দোকানের সহজ ড্যাশবোর্ড।",
    "label.good_morning_rina": "সুপ্রভাত, রিনা",
    "label.customer_dashboard": "ক্রেতা ড্যাশবোর্ড",
    "label.now_live_across_bangladesh": "বাংলাদেশজুড়ে এখন চালু",
    "label.local_shops": "স্থানীয় দোকান",
    "label.active_users": "সক্রিয় ব্যবহারকারী",
    "label.orders_day": "প্রতিদিনের অর্ডার",
    "label.all_systems_live": "সব সিস্টেম সচল",
    "label.total_orders": "মোট অর্ডার",
    "label.baki_balance": "বাকি ব্যালেন্স",
    "label.preparing": "প্রস্তুত হচ্ছে",
    "label.delivered": "ডেলিভারি হয়েছে",
    "label.product": "পণ্য",
    "label.resources": "রিসোর্স",
    "label.company": "কোম্পানি",
    "label.documentation": "ডকুমেন্টেশন",
    "label.help_center": "সহায়তা কেন্দ্র",
    "label.blog": "ব্লগ",
    "label.about": "সম্পর্কে",
    "label.careers": "ক্যারিয়ার",
    "label.privacy_policy": "গোপনীয়তা নীতি",
    "label.terms_of_service": "সেবার শর্তাবলি",
    "label.create_account": "অ্যাকাউন্ট তৈরি করুন",
    "label.send_otp": "OTP পাঠান",
    "label.verify_otp": "OTP যাচাই করুন",
    "label.google": "গুগল",
    "label.quick_actions": "দ্রুত কাজ",
    "label.find_nearby_shops": "কাছের দোকান খুঁজুন",
    "label.shops_within_1_km": "১ কিমির মধ্যে দোকান",
    "label.place_an_order": "অর্ডার দিন",
    "label.order_from_a_shop": "দোকান থেকে অর্ডার করুন",
    "label.recent_orders": "সাম্প্রতিক অর্ডার",
    "label.no_payments_yet": "এখনও কোনো পেমেন্ট নেই",
    "label.payment_history": "পেমেন্টের ইতিহাস",
    "label.pay_baki_balance": "বাকির টাকা পরিশোধ করুন",
    "label.select_baki": "বাকি নির্বাচন করুন",
    "label.amount_bdt": "পরিমাণ (টাকা)",
    "label.payment_method": "পেমেন্ট পদ্ধতি",
    "label.my_profile": "আমার প্রোফাইল",
    "label.manage_your_account_information": "আপনার অ্যাকাউন্টের তথ্য পরিচালনা করুন",
    "label.full_name": "পুরো নাম",
    "label.phone_number": "ফোন নম্বর",
    "label.prefer_not_to_say": "জানাতে চাই না",
    "label.my_baki": "আমার বাকি",
    "label.request_baki_membership": "বাকি সদস্যপদের অনুরোধ করুন",
    "label.request": "অনুরোধ করুন",
    "label.add": "যোগ করুন",
    "label.save": "সংরক্ষণ করুন",
    "label.active_members": "সক্রিয় সদস্য",
    "label.purchase_history": "কেনাকাটার ইতিহাস",
    "label.product_details": "পণ্যের বিবরণ",
    "label.phone_unavailable": "ফোন পাওয়া যায়নি",
    "label.address_unavailable": "ঠিকানা পাওয়া যায়নি",
    "label.open": "খোলা",
    "label.closed": "বন্ধ",
    "label.open_by_schedule_button": "সময়সূচি অনুযায়ী খোলা",
    "label.closed_by_schedule_button": "সময়সূচি অনুযায়ী বন্ধ",
    "label.save_opening_hours": "খোলার সময় সংরক্ষণ করুন",
    "label.update_failed": "আপডেট ব্যর্থ হয়েছে",
    "label.schedule_updated": "খোলার সময়সূচি সফলভাবে আপডেট হয়েছে",
    "label.shopkeeper_confirms_final_amount_placeholder": "দোকানদার চূড়ান্ত পরিমাণ নিশ্চিত করবেন",
    "label.select_baki_enter_amount": "বাকি নির্বাচন করে পরিমাণ লিখুন",
    "label.payment_failed": "পেমেন্ট ব্যর্থ হয়েছে",
    "label.delete_sale_confirm": "এই বিক্রয়ের রেকর্ড মুছবেন?",
    "label.credit_limit": "ক্রেডিট সীমা",
    "label.limit": "সীমা",
    "label.no_limit": "কোনো সীমা নেই",
    "label.set_credit_limit": "সীমা সেট করুন",
    "label.add_credit_customer": "ক্রেডিট গ্রাহক যোগ করুন",
    "label.add_purchase": "ক্রয় যোগ করুন",
    "label.member_id": "সদস্য আইডি",
    "label.customer_details": "গ্রাহকের তথ্য",
    "label.credit_customer_details": "ক্রেডিট গ্রাহকের তথ্য",
    "label.view_details": "বিস্তারিত দেখুন",
    "label.remove": "অপসারণ",
    "label.remove_baki_member": "বাকি সদস্য অপসারণ করুন",
    "label.confirm_delete": "মুছে ফেলার বিষয়টি নিশ্চিত করুন?",
    "label.confirm_update": "আপডেট নিশ্চিত করুন?",
    "label.confirm_update_description": "আপনি কি এই আপডেটটি সংরক্ষণ করতে চান?",
    "label.update_success": "সফলভাবে আপডেট হয়েছে",
    "label.delete_success": "সফলভাবে মুছে ফেলা হয়েছে",
    "label.credit_customer_nid_help": "ক্রেডিট রেকর্ডের জন্য গ্রাহকের তথ্য এবং NID-এর দুই পাশ সংরক্ষণ করুন।",
    "label.nid_number": "NID নম্বর",
    "label.nid_front": "NID-এর সামনের ছবি",
    "label.nid_back": "NID-এর পেছনের ছবি",
    "label.search_credit_members": "আইডি, নাম, ফোন বা ইমেইল দিয়ে খুঁজুন",
    "nearby.use_current_location": "বর্তমান অবস্থান ব্যবহার করুন",
    "nearby.using_saved_location": "আপনার সংরক্ষিত প্রোফাইলের অবস্থান ব্যবহার করা হচ্ছে",
    "nearby.set_location_first": "প্রোফাইলে অবস্থান সেট করুন অথবা বর্তমান অবস্থান ব্যবহার করুন।",
    "nearby.location_permission": "অবস্থান ব্যবহারের অনুমতি দেওয়া হয়নি বা অবস্থান পাওয়া যায়নি। ব্রাউজারে অনুমতি দিয়ে আবার চেষ্টা করুন।",
    "nearby.location_unavailable": "এই ব্রাউজারে অবস্থান সেবা নেই।",
    "label.no_baki_memberships_yet": "এখনও কোনো বাকি সদস্যপদ নেই",
    "label.outstanding": "বকেয়া",
    "label.track_all_your_orders": "আপনার সব অর্ডার দেখুন",
    "label.no_orders_yet": "এখনও কোনো অর্ডার নেই",
    "label.place_your_first_order_from_a_nearby_shop": "কাছের দোকান থেকে আপনার প্রথম অর্ডার দিন",
    "label.nearby_shops": "কাছের দোকান",
    "label.live": "সচল",
    "label.baki": "বাকি",
    "label.nearby": "কাছাকাছি",
    "label.closest_shop": "কাছের দোকান",
    "label.digital_baki": "ডিজিটাল বাকি",
    "label.open_shops_near_you": "আপনার কাছের খোলা দোকান",
    "label.everything_in_one_view": "এক নজরে সবকিছু",
    "label.current_balance": "বর্তমান ব্যালেন্স",
    "label.monthly_limit": "মাসিক সীমা",
    "label.local_first": "স্থানীয়ভাবে শুরু",
    "label.discovery_1km": "১ কিমির মধ্যে খোঁজ",
    "label.secure_checkout": "নিরাপদ চেকআউট",
    "label.no_shops_found_nearby": "কাছাকাছি কোনো দোকান পাওয়া যায়নি",
    "label.order_placed": "অর্ডার দেওয়া হয়েছে!",
    "label.quantity": "পরিমাণ",
    "label.payment_option": "পেমেন্টের বিকল্প",
    "label.not_approved_for_this_shop": "এই দোকানের জন্য অনুমোদিত নয়",
    "label.estimated_amount_bdt": "আনুমানিক পরিমাণ (টাকা)",
    "label.online_payment_provider": "অনলাইন পেমেন্ট প্রদানকারী",
    "label.choose_a_nearby_shop": "কাছের দোকান বেছে নিন...",
    "label.what_do_you_need": "আপনার কী প্রয়োজন?",
    "label.delivery_notes": "ডেলিভারি সংক্রান্ত নোট",
    "label.optional": "ঐচ্ছিক",
    "label.todays_revenue": "আজকের আয়",
    "label.total_revenue": "মোট আয়",
    "label.avg_sale": "গড় বিক্রয়",
    "label.sales_count": "বিক্রয়",
    "label.total_sales": "মোট বিক্রয়",
    "label.per_transaction": "প্রতি লেনদেনে",
    "label.rice_placeholder": "যেমন: ২ কেজি চাল",
    "label.save_sale": "বিক্রয় সংরক্ষণ করুন",
    "label.add_sale": "বিক্রয় যোগ করুন",
    "label.cancel": "বাতিল",
    "label.optional_note": "ঐচ্ছিক নোট",
    "label.cash_on_delivery": "ক্যাশ অন ডেলিভারি",
    "label.online": "অনলাইন",
    "label.card_stripe": "কার্ড / Stripe",
    "label.mfs_sslcommerz": "বিকাশ / নগদ",
    "label.open_by_schedule": "সময়সূচি অনুযায়ী খোলা",
    "label.closed_by_schedule": "সময়সূচি অনুযায়ী বন্ধ",
    "label.baki_management": "বাকি ব্যবস্থাপনা",
    "label.manage_customer_credit_accounts": "ক্রেতাদের ক্রেডিট অ্যাকাউন্ট পরিচালনা করুন",
    "label.nearby_customers": "কাছের ক্রেতা",
    "label.add_to_baki": "বাকিতে যোগ করুন",
    "label.add_baki_customer_manually": "ম্যানুয়ালি বাকি ক্রেতা যোগ করুন",
    "label.no_active_baki_members": "কোনো সক্রিয় বাকি সদস্য নেই",
    "label.orders": "অর্ডার",
    "label.manage_incoming_customer_orders": "আসা ক্রেতার অর্ডার পরিচালনা করুন",
    "label.all_orders": "সব অর্ডার",
    "label.no_orders_found": "কোনো অর্ডার পাওয়া যায়নি",
    "label.not_specified": "উল্লেখ করা হয়নি",
    "label.final_amount_bdt": "চূড়ান্ত পরিমাণ (টাকা)",
    "label.update": "আপডেট",
    "label.sales": "বিক্রয়",
    "label.track_your_daily_sales": "আপনার দৈনিক বিক্রয় দেখুন",
    "label.record_new_sale": "নতুন বিক্রয়记录 করুন",
    "label.item_name": "পণ্যের নাম *",
    "label.item": "পণ্য",
    "label.select_shop": "দোকান নির্বাচন করুন",
    "label.price": "মূল্য (টাকা) *",
    "label.customer_name": "ক্রেতার নাম",
    "label.customer_phone": "ক্রেতার ফোন",
    "label.note": "নোট",
    "label.no_sales_recorded_yet": "এখনও কোনো বিক্রয় রেকর্ড নেই",
    "label.shop": "দোকান",
    "label.items": "পণ্যসমূহ",
    "label.status": "অবস্থা",
    "label.date": "তারিখ",
    "label.customer": "ক্রেতা",
    "label.amount": "পরিমাণ",
    "label.method": "পদ্ধতি",
    "label.action": "অ্যাকশন",
    "label.shop_profile": "দোকান ও প্রোফাইল",
    "label.manage_your_shop_and_personal_info": "দোকান ও ব্যক্তিগত তথ্য পরিচালনা করুন",
    "label.opening_hours": "খোলার সময়",
    "label.use_schedule": "সময়সূচি ব্যবহার করুন",
    "label.personal_information": "ব্যক্তিগত তথ্য",
    "label.shop_location": "দোকানের অবস্থান",
    "label.save_changes": "পরিবর্তন সংরক্ষণ করুন",
    "label.subscription_plan": "সাবস্ক্রিপশন প্ল্যান",
    "label.popular": "জনপ্রিয়",
    "label.review_and_verify_customer_payments": "ক্রেতাদের পেমেন্ট পর্যালোচনা ও যাচাই করুন",
    "label.welcome_back": "আবার স্বাগতম",
    "label.hello": "হ্যালো",
    "label.welcome": "স্বাগতম",
    "label.customer_space": "ক্রেতার অংশ",
    "label.shopkeeper_space": "দোকানদারের অংশ",
    "label.your_shop_dashboard": "আপনার দোকানের ড্যাশবোর্ড",
    "label.view_all": "সব দেখুন",
    "label.shop_is_open": "দোকান খোলা",
    "label.shop_is_closed": "দোকান বন্ধ",
    "label.neighborhood_update": "আজ আপনার এলাকায় কী ঘটছে তা দেখুন।",
    "label.create_your_account": "আপনার অ্যাকাউন্ট তৈরি করুন",
    "label.sign_in_to_your_neighborhood": "আপনার পাড়ায় সাইন ইন করুন",
    "label.join_parar_dokan_today": "আজই পাড়ার দোকানে যোগ দিন",
    "label.sign_in": "সাইন ইন",
    "label.register": "রেজিস্টার",
    "label.i_am_a": "আমি একজন...",
    "label.avatar": "প্রোফাইল ছবি",
    "label.select_shop_label": "দোকান নির্বাচন করুন",
    "label.payments": "পেমেন্ট",
    "label.pay_your_baki_balance": "আপনার বাকি পরিশোধ করুন",
    "label.choose": "নির্বাচন করুন...",
    "label.enter_amount": "পরিমাণ লিখুন",
    "label.my_orders": "আমার অর্ডার",
    "label.items_colon": "পণ্য:",
    "label.quantity_colon": "পরিমাণ:",
    "label.total_received": "মোট প্রাপ্তি",
    "label.pending": "অপেক্ষমাণ",
    "label.verified": "যাচাইকৃত",
    "label.confirm_delete_sale": "এই বিক্রয়ের রেকর্ড মুছবেন?",
    "label.customers_within_1km": "আপনার দোকানের ১ কিমির মধ্যে থাকা এবং বাকির তালিকায় নেই এমন ক্রেতারা।",
    "label.shopkeeper_confirms_amount": "দোকানদার চূড়ান্ত পরিমাণ নিশ্চিত করবেন",
    "label.required_to_approve": "অনুমোদনের জন্য আবশ্যক",
    "label.enter_quantity": "যেমন: ২ কেজি, ৫০০ গ্রাম, ১ বোতল",
    "label.order_placeholder": "যেমন: ২ কেজি চাল, ৫০০ গ্রাম চিনি, ১ বোতল তেল, ৬টি ডিম...",
    "label.delivery_placeholder": "যেমন: সন্ধ্যা ৬টার আগে ডেলিভারি দিন",
    "label.your_neighborhood": "আপনার এলাকা",
    "label.customer_name_placeholder": "ক্রেতার নাম",
    "label.phone_number_placeholder": "ফোন নম্বর",
  },
};

const ThemeContext = createContext<ThemeContextType>({
  theme: "light",
  lang: "en",
  toggleTheme: () => {},
  toggleLang: () => {},
  t: (k) => k,
});

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>(
    () => (localStorage.getItem("theme") as Theme) || "light"
  );
  const [lang, setLang] = useState<Lang>(
    () => (localStorage.getItem("lang") as Lang) || "en"
  );

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    if (theme === "dark") document.documentElement.classList.add("dark");
    else document.documentElement.classList.remove("dark");
    localStorage.setItem("theme", theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.setAttribute("data-lang", lang);
  }, [lang]);

  const toggleTheme = useCallback(
    () => setTheme((t) => (t === "light" ? "dark" : "light")),
    []
  );
  const toggleLang = useCallback(
    () => setLang((l) => (l === "en" ? "bn" : "en")),
    []
  );
  const t = useCallback(
    (key: string) => translations[lang][key] || translations.en[key] || key,
    [lang]
  );
  const value = useMemo(
    () => ({ theme, lang, toggleTheme, toggleLang, t }),
    [theme, lang, toggleTheme, toggleLang, t]
  );

  return (
    <ThemeContext.Provider value={value}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  return useContext(ThemeContext);
}
